### PR TITLE
Add DOCTYPE to avoid quirks mode

### PR DESCRIPTION
**Pull request by abitrolly**
https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode

### CODE REVIEW

**Review by tbicr — APPROVED** [review]

**Comment by abitrolly** [comment]
Nice. Still don't see this change at https://openstreetmap.by/

Is it because the deployment is not automated? Or because the old version is still cached?

**Comment by abitrolly** [comment]
But is there at least a single `deploy.sh` script that executes all the necessary logic?

For some reason I got a feeling that getting rid of quirks mode may help with #37, but on the second thought the #37 looks like a completely backend problem.

**Comment by tbicr** [comment]
> But is there at least a single deploy.sh script that executes all the necessary logic?

only some automatization: https://github.com/osm-by/OpenStreetMap.by#initialize-project

**Comment by abitrolly** [comment]
So basically, to make this change live, the procedure is to log in into server, update the code and restart server.
```
cd /home/ubuntu/OpenStreetMap.by
git pull
```
Is that it?
I didn't include the step to restart Nginx. It should be able to serve changed static files automatically.

**Pull request merged**
